name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: pylinter
      uses: programmingwithalex/pylinter@v1.4.3
      with:
        # Optional: specify the directory to run linters on
        python-root: .
        # Optional: specify flags for flake8
        flake8-flags: '--max-line-length=79'
        # Optional: specify flags for mypy
        mypy-flags: '--ignore-missing-imports'
        # Optional: fail the job if isort changes are needed
        fail-on-isort: true
        # Optional: skip flake8 checks
        skip-flake8: false
        # Optional: skip mypy checks
        skip-mypy: false
        # Optional: skip isort checks
        skip-isort: false
        # Optional: list of directories and/or files to ignore for mypy
        mypy-ignore-dirs-files: 'tests/*'
        # Optional: requirements file for mypy to prevent library stub missing errors
        requirements-file: 'requirements.txt'