name: Hugging Face Login

on:
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Hugging Face Hub
        uses: osbm/huggingface_login@v0.1
        with:
          username: ${{ secrets.HF_USERNAME }}
          password: ${{ secrets.HF_PASSWORD }}
          add_to_git_credentials: true

      - name: Check if logged in
        run: |
          huggingface-cli whoami
